package model

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// DBArticle model info
// @Description Article's information with autogenerated id
type DBArticle struct {
	ID          primitive.ObjectID `bson:"_id,omitempty"` // Autogenerated id
	Title       string             `bson:"title"`         // Title of an article
	Created     time.Time          `bson:"created"`       // Date and time of publication of an article, format ISO 8601, example "2022-12-22T20:57:12Z"
	Author      string             `bson:"author"`        // Authors of an article
	Description string             `bson:"summary"`       // Descripton of an article
	URL         string             `bson:"url"`           // Permanent link to an article
}
