package model

import (
	"time"
)

// DBArticle model info
// @Description Article's information with autogenerated id
type DBArticle struct {
	ID          interface{} `bson:"_id,omitempty"` // Autogenerated id, format depends of dbms type
	Title       string      `bson:"title"`         // Title of an article
	Created     time.Time   `bson:"created"`       // Date and time of publication of an article, format ISO 8601, example "2022-12-22T20:57:12Z"
	Author      string      `bson:"author"`        // Authors of an article
	Description string      `bson:"summary"`       // Descripton of an article
	URL         string      `bson:"url"`           // Permanent link to an article
}
