definitions:
  model.DBArticle:
    properties:
      author:
        type: string
      created:
        type: string
      description:
        type: string
      id:
        type: string
      title:
        type: string
      url:
        type: string
    type: object
info:
  contact:
    email: aggregator_lets_go@gmail.com
    name: Web-Service Support
  description: Swagger Web-Service for Let's Go Aggregator
  termsOfService: http://swagger.io/terms/
  title: Web-Service Swagger
  version: 1.0.1
paths:
  /last_news:
    get:
      description: Get array of Articles for the last 7 days
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.DBArticle'
            type: array
      summary: Retrieves news from last 7 days
      tags:
        - news
swagger: "2.0"
