version: '3.9'

services:

  webservice:
    image: tsherbinin5/webservice:latest
    container_name: web-service
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./Dockerfile.webservice
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - aggregatorNet

  aggregator:
    image: tsherbinin5/aggregator:latest
    container_name: aggregator
    build:
      context: .
      dockerfile: ./Dockerfile.aggregator
    depends_on:
      - mongodb
    networks:
      - aggregatorNet
    links:
      - mongodb

  mongodb:
    image: mvertes/alpine-mongo:4.0.6-1
    container_name: mongodb
    networks:
      - aggregatorNet

networks:
  aggregatorNet:
    driver: bridge
