version: '3.9'

services:

  webservice:
    image: web-service
    container_name: web-service
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: ./Dockerfile.webservice
    depends_on:
      - mongodb
      - aggregator
    links:
      - mongodb
    networks:
      - aggregatorNet

  aggregator:
    image: aggregator
    container_name: aggregator
    ports:
      - 3306:3306
    build:
      context: .
      dockerfile: ./Dockerfile.aggregator
    depends_on:
      - mongodb
    networks:
      - aggregatorNet
    links:
      - mongodb

  mongodb:
    image: mvertes/alpine-mongo
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - aggregatorNet

networks:
  aggregatorNet:
    driver: bridge