FROM golang:1.18.7-alpine AS builder

RUN go version

COPY ./ /github.com/indikator/aggregator_lets_go
WORKDIR /github.com/indikator/aggregator_lets_go

RUN go mod download && go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o ./.bin/app ./cmd/webservice/main.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates
WORKDIR /root

COPY --from=builder /github.com/indikator/aggregator_lets_go/.bin/app .
ADD configs ./configs

CMD [ "./app"]