version: '3.9'

services:

  webservice:
    image: web-service
    container_name: web-service
    ports: 
      - "80:8080"
    build:
      context: .
      dockerfile: ./Dockerfile.webservice
    depends_on:
       - mongo
       - aggregator
    links:
      - mongo

  aggregator:
    image: aggregator
    container_name: aggregator
    ports:
      - 3306:3306
    build:
      context: .
      dockerfile: ./Dockerfile.aggregator
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
