# Project Aggregator YAML
aggregator:
  log:
    type: std
    level: errors

database:
  name: mongo
  url: mongodb://mongodb:27017

webservice:
  handle: /last_news
  port: 8080
  log:
    type: std
    level: error

parsers:
- github:
    url: https://github.com/golang/go/tags
- go.dev:
    url: https://go.dev/blog
- medium.com:
    url: https://medium.com/_/graphql
