# Project Aggregator YAML
aggregator:
  nothing:

database:
  name: mongo
  url: mongodb://mongodb:27017

webservice:
  port: 8080
  handle: /last_news

parsers:
- github:
    url: https://github.com/golang/go/tags
- go.dev:
    url: https://go.dev/blog
- medium.com:
    url: https://medium.com/_/graphql