# Project Aggregator YAML
aggregator:
  logLevel: errors

database:
  name: mongo
  url: mongodb://mongodb:27017
  logLevel: errors

webservice:
  - last_news:
      handle: /last_news
      port: 8080
      logLevel: errors

parsers:
- github:
    url: https://github.com/golang/go/tags
    logLevel: errors
- go.dev:
    url: https://go.dev/blog
    logLevel: errors
- medium.com:
    url: https://medium.com/_/graphql
    logLevel: errors
