name: Common

on: [workflow_call]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install dependencies
        run: go get -v ./...

      - name: Test
        run: go test -v ./...
        
      - name: Coverage
        run: go test -v -coverprofile cover.out ./...
        
      - name: Coverage Report
        run: go tool cover -html cover.out -o cover.html
        
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: cover.html
          path: cover.html
          retention-days: 15
